<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Session;
use Auth;
use DB;
use Mail;
use PDF;
use Illuminate\Support\Facades\Hash;

class AlgoritmaController extends Controller
{
    public function index(){
    // $findKasus = DB::table('pasien as p')
    //                     ->join('kasus as k','p.kode_kasus','=','k.Kode_kasus')
    //                     ->join('detail_gejala as dg','dg.kode_kasus','=','k.Kode_kasus')
    //                     ->join('gejala as g','g.kode_gejala','=','dg.Kode_gejala')
    //                     ->select('p.Usia', 'p.Jenis_kelamin', 'p.Kondisi', 'p.Kesadaran', 'p.nyeri_kepala', 'p.TS', 'p.TD', 'p.Suhu', 'p.Nafas', 
    //                     'p.Denyut_nadi', 'k.Kode_kasus', 'k.kode_penyakit', 'g.kode_gejala')
    //                     ->where('dg.nilai',1)
    //                     ->orderBy('k.kode_kasus', 'desc')
    //                     ->orderBy('g.kode_gejala', 'desc')
    //                     ->get();

    $findKasus = DB::table('pasien as p')
                        ->join('kasus as k','p.kode_kasus','=','k.Kode_kasus')
                        ->join('detail_gejala as dg','dg.kode_kasus','=','k.Kode_kasus')
                        ->join('gejala as g','g.kode_gejala','=','dg.Kode_gejala')
                        ->select('k.Kode_kasus', 'k.kode_penyakit', 'g.kode_gejala')
                        ->where('dg.nilai',1)
                        ->orderBy('k.kode_kasus', 'desc')
                        ->orderBy('g.kode_gejala', 'desc')
                        ->get();
        
        //generate gejala 1 sampai 43
        $arr_data2 = array();
        $tmp_kode_kasus = '';
        $count = 0;
        $obj = json_decode($findKasus);
        
        foreach ($obj as $key => $value) {
            if($tmp_kode_kasus != $value->Kode_kasus){
                $tmp_kode_kasus =  $value->Kode_kasus;
                // $arr_data2[] = array(
                //     "Kode_kasus" => $value->Kode_kasus,
                //     "kode_penyakit" => $value->kode_penyakit,
                //     "G1" => 0,
                //     "G2" => 0,
                //     "G3" => 0,
                //     "G4" => 0,
                //     "G5" => 0,
                //     "G6" => 0,
                //     "G7" => 0,
                //     "G8" => 0,
                //     "G9" => 0,
                //     "G10" => 0,
                //     "G11" => 0,
                //     "G12" => 0,
                //     "G13" => 0,
                //     "G14" => 0,
                //     "G15" => 0,
                //     "G16" => 0,
                //     "G17" => 0,
                //     "G18" => 0,
                //     "G19" => 0,
                //     "G20" => 0,
                //     "G21" => 0,
                //     "G22" => 0,
                //     "G23" => 0,
                //     "G24" => 0,
                //     "G25" => 0,
                //     "G26" => 0,
                //     "G27" => 0,
                //     "G28" => 0,
                //     "G29" => 0,
                //     "G30" => 0,
                //     "G31" => 0,
                //     "G32" => 0,
                //     "G33" => 0,
                //     "G34" => 0,
                //     "G35" => 0,
                //     "G36" => 0,
                //     "G37" => 0,
                //     "G38" => 0,
                //     "G39" => 0,
                //     "G40" => 0,
                //     "G41" => 0,
                //     "G42" => 0,
                //     "G43" => 0,
                // );
                $arr_data2[] = array(
                    "Kode_kasus" => $value->Kode_kasus,
                    "kode_penyakit" => $value->kode_penyakit,
                    "G1" => "False",
                    "G2" => "False",
                    "G3" => "False",
                    "G4" => "False",
                    "G5" => "False",
                    "G6" => "False",
                    "G7" => "False",
                    "G8" => "False",
                    "G9" => "False",
                    "G10" => "False",
                    "G11" => "False",
                    "G12" => "False",
                    "G13" => "False",
                    "G14" => "False",
                    "G15" => "False",
                    "G16" => "False",
                    "G17" => "False",
                    "G18" => "False",
                    "G19" => "False",
                    "G20" => "False",
                    "G21" => "False",
                    "G22" => "False",
                    "G23" => "False",
                    "G24" => "False",
                    "G25" => "False",
                    "G26" => "False",
                    "G27" => "False",
                    "G28" => "False",
                    "G29" => "False",
                    "G30" => "False",
                    "G31" => "False",
                    "G32" => "False",
                    "G33" => "False",
                    "G34" => "False",
                    "G35" => "False",
                    "G36" => "False",
                    "G37" => "False",
                    "G38" => "False",
                    "G39" => "False",
                    "G40" => "False",
                    "G41" => "False",
                    "G42" => "False",
                    "G43" => "False",
                );
                $arr_data2[$count][$value->kode_gejala] = "True";
                $count++;
            }else{
                $arr_data2[$count-1][$value->kode_gejala] = "True";
            }
        }

        $tmp1 = json_encode($arr_data2);
        $tmp2 = json_decode($tmp1);

        $arrUji2 = [
            [
                "Kasus" => "K00001",
                "Nama" => "Bp Sugiarto",
                "Alamat" => "Kusbini",
                "usia" => "50",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "0",
                "nyeri kepala" => "4",
                "TS" => "130",
                "TD" => "95",
                "suhu" => "36.5",
                "nafas" => "22",
                "denyut nadi" => "88",
                "tgl diagnosis" => "12/04/2016",
                "Diagnosis" => "Thrombosis Stroke",
                "Gejala" => "G1, G4, G7, G9, G10, G15, G20, G25, G27, G35, G40",
                "Faktor Risiko" => "FR1, FR2, FR11",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00090",
                "Nama" => "Jamal",
                "usia" => "50",
                "jenis kelamin" => "1",
                "kondisi" => "2",
                "kesadaran" => "2",
                "nyeri kepala" => "8",
                "TS" => "180",
                "TD" => "110",
                "suhu" => "38.5",
                "nafas" => "26",
                "denyut nadi" => "96",
                "tgl diagnosis" => "09/01/2017 00:00:00",
                "Diagnosis" => "Subarachnoid hemorrhage Stroke",
                "Gejala" =>
                    "G5, G6, G8, G13, G14, G15, G16, G27, G28, G29, G32, G34, G35, G36, G41, G42, G43",
                "Faktor Risiko" => "FR2, FR7, FR8",
                "Tingkat Keyakinan(%)" => "95",
            ],
            [
                "Kasus" => "K00092",
                "Nama" => "Wahyudi",
                "usia" => "48",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "0",
                "nyeri kepala" => "2",
                "TS" => "190",
                "TD" => "100",
                "suhu" => "38",
                "nafas" => "28",
                "denyut nadi" => "96",
                "tgl diagnosis" => "07/04/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" =>
                    "G1, G4, G7, G10, G12, G15, G20, G27, G28, G31, G33, G35, G37, G38, G40, G41, G42, G43",
                "Faktor Risiko" => "FR5, FR7, FR8, FR11",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00012",
                "Nama" => "Indah Gunawan",
                "Alamat" => "Iromejan",
                "usia" => "57",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "0",
                "nyeri kepala" => "0",
                "TS" => "160",
                "TD" => "100",
                "suhu" => "36",
                "nafas" => "20",
                "denyut nadi" => "86",
                "tgl diagnosis" => "21/01/2016 00:00:00",
                "Diagnosis" => "Thrombosis Stroke",
                "Gejala" => "G4, G5, G7, G10, G15, G20, G25, G28, G30, G35, G40, G42",
                "Faktor Risiko" => "FR2",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00062",
                "Nama" => "Dwi Sartika",
                "usia" => "58",
                "jenis kelamin" => "0",
                "kondisi" => "2",
                "kesadaran" => "1",
                "nyeri kepala" => "6",
                "TS" => "130",
                "TD" => "80",
                "suhu" => "36.5",
                "nafas" => "22",
                "denyut nadi" => "90",
                "tgl diagnosis" => "15/03/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" =>
                    "G1, G4, G7, G8, G10, G11, G12, G15, G17, G18, G20, G22, G23, G25, G27, G28, G29, G35, G41",
                "Faktor Risiko" => "FR2, FR3, FR8, FR10",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00048",
                "Nama" => "Dewi",
                "usia" => "68",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "8",
                "TS" => "130",
                "TD" => "95",
                "suhu" => "36.5",
                "nafas" => "28",
                "denyut nadi" => "86",
                "tgl diagnosis" => "12/03/2016 00:00:00",
                "Diagnosis" => "Intracerebral hemorrhage Stroke",
                "Gejala" =>
                    "G2, G3, G6, G7, G9, G14, G15, G16, G27, G29, G32, G34, G35, G36",
                "Faktor Risiko" => "FR3, FR6, FR7, FR10",
                "Tingkat Keyakinan(%)" => "95",
            ],
            [
                "Kasus" => "K00095",
                "Nama" => "Rahma",
                "Alamat" => "Iromejan",
                "usia" => "67",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "0",
                "nyeri kepala" => "5",
                "TS" => "180",
                "TD" => "100",
                "suhu" => "37",
                "nafas" => "22",
                "denyut nadi" => "80",
                "tgl diagnosis" => "16/03/2016 00:00:00",
                "Diagnosis" => "Thrombosis Stroke",
                "Gejala" => "G1, G3, G9, G10, G14, G16, G27, G31, G35, G38, G41, G42",
                "Faktor Risiko" => "FR2, FR7, FR8",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00003",
                "Nama" => "Bp Dursin",
                "usia" => "53",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "0",
                "nyeri kepala" => "0",
                "TS" => "190",
                "TD" => "90",
                "suhu" => "36",
                "nafas" => "21",
                "denyut nadi" => "88",
                "tgl diagnosis" => "28/07/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" => "G4, G7, G8, G9, G10, G15, G20, G25, G27, G40, G41",
                "Faktor Risiko" => "FR1, FR5, FR11",
                "Tingkat Keyakinan(%)" => "95",
            ],
            [
                "Kasus" => "K00074",
                "Nama" => "Bernat",
                "usia" => "72",
                "jenis kelamin" => "1",
                "kondisi" => "0",
                "kesadaran" => "0",
                "nyeri kepala" => "0",
                "TS" => "170",
                "TD" => "90",
                "suhu" => "36.5",
                "nafas" => "20",
                "denyut nadi" => "93",
                "tgl diagnosis" => "15/03/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" =>
                    "G4, G7, G8, G11, G12, G20, G25, G27, G28, G29, G31, G34, G35",
                "Faktor Risiko" => "FR2, FR8",
                "Tingkat Keyakinan(%)" => "95",
            ],
            [
                "Kasus" => "K00071",
                "Nama" => "Eva",
                "usia" => "56",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "6",
                "TS" => "140",
                "TD" => "95",
                "suhu" => "38.2",
                "nafas" => "18",
                "denyut nadi" => "96",
                "tgl diagnosis" => "23/04/2016 00:00:00",
                "Diagnosis" => "Subarachnoid hemorrhage Stroke",
                "Gejala" => "G4, G5, G6, G13, G14, G16, G37, G38, G42, G43",
                "Faktor Risiko" => "FR2, FR7, FR8",
                "Tingkat Keyakinan(%)" => "85",
            ],
            [
                "Kasus" => "K00070",
                "Nama" => "Heru K",
                "usia" => "51",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "0",
                "nyeri kepala" => "0",
                "TS" => "120",
                "TD" => "90",
                "suhu" => "37",
                "nafas" => "22",
                "denyut nadi" => "88",
                "tgl diagnosis" => "25/07/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" => "G1, G4, G7, G10, G11, G12, G20, G28, G29, G38",
                "Faktor Risiko" => "FR2, FR8, FR10, FR11",
                "Tingkat Keyakinan(%)" => "92",
            ],
            [
                "Kasus" => "K00154",
                "Nama" => "Yoela",
                "Alamat" => "Garuda",
                "usia" => "69",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "0",
                "nyeri kepala" => "3",
                "TS" => "150",
                "TD" => "90",
                "suhu" => "36.5",
                "nafas" => "21",
                "denyut nadi" => "82",
                "tgl diagnosis" => "12/04/2016 00:00:00",
                "Diagnosis" => "Thrombosis Stroke",
                "Gejala" =>
                    "G1, G3, G4, G7, G8, G9, G10, G11, G14, G15, G16, G27, G35, G37, G40, G42",
                "Faktor Risiko" => "FR2, FR7, FR8",
                "Tingkat Keyakinan(%)" => "95",
            ],
            [
                "Kasus" => "K00155",
                "Nama" => "Adi",
                "Alamat" => "Iromejan",
                "usia" => "58",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "0",
                "nyeri kepala" => "0",
                "TS" => "170",
                "TD" => "100",
                "suhu" => "37",
                "nafas" => "20",
                "denyut nadi" => "80",
                "tgl diagnosis" => "07/03/2016 00:00:00",
                "Diagnosis" => "Thrombosis Stroke",
                "Gejala" =>
                    "G1, G3, G4, G8, G9, G10, G11, G12, G14, G15, G16, G27, G31, G35, G40, G41, G42",
                "Faktor Risiko" => "FR2, FR3, FR8",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00028",
                "Nama" => "Tri Ayu",
                "usia" => "74",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "3",
                "TS" => "120",
                "TD" => "100",
                "suhu" => "38",
                "nafas" => "22",
                "denyut nadi" => "88",
                "tgl diagnosis" => "01/03/2016 00:00:00",
                "Diagnosis" => "Subarachnoid hemorrhage Stroke",
                "Gejala" =>
                    "G1, G2, G3, G4, G6, G7, G9, G11, G12, G13, G14, G15, G16, G19, G21, G22, G23, G24, G25, G26, G27, G28, G29, G30, G32, G33, G36, G38, G41, G43",
                "Faktor Risiko" => "FR2, FR3, FR8, FR10",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00023",
                "Nama" => "Sutanto",
                "usia" => "86",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "3",
                "TS" => "150",
                "TD" => "90",
                "suhu" => "36",
                "nafas" => "20",
                "denyut nadi" => "80",
                "tgl diagnosis" => "03/01/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" => "G4, G7, G8, G10, G15, G27, G28, G32, G35, G37, G38, G40",
                "Faktor Risiko" => "FR11",
                "Tingkat Keyakinan(%)" => "92",
            ],
            [
                "Kasus" => "K00158",
                "Nama" => "Herlinda",
                "Alamat" => "Garuda",
                "usia" => "52",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "0",
                "TS" => "180",
                "TD" => "100",
                "suhu" => "36.5",
                "nafas" => "20",
                "denyut nadi" => "94",
                "tgl diagnosis" => "02/06/2016 00:00:00",
                "Diagnosis" => "Thrombosis Stroke",
                "Gejala" =>
                    "G1, G8, G10, G13, G15, G16, G25, G27, G28, G29, G30, G35, G37, G39, G40, G42",
                "Faktor Risiko" => "FR1, FR2, FR3, FR11",
                "Tingkat Keyakinan(%)" => "95",
            ],
            [
                "Kasus" => "K00159",
                "Nama" => "Chandra",
                "Alamat" => "Iromejan",
                "usia" => "59",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "0",
                "nyeri kepala" => "0",
                "TS" => "140",
                "TD" => "90",
                "suhu" => "36",
                "nafas" => "22",
                "denyut nadi" => "82",
                "tgl diagnosis" => "18/04/2016 00:00:00",
                "Diagnosis" => "Thrombosis Stroke",
                "Gejala" =>
                    "G1, G3, G4, G7, G8, G9, G10, G11, G14, G15, G16, G27, G35, G37, G40",
                "Faktor Risiko" => "FR2, FR4, FR8",
                "Tingkat Keyakinan(%)" => "95",
            ],
            [
                "Kasus" => "K00115",
                "Nama" => "Yunem",
                "Alamat" => "Iromejan",
                "usia" => "64",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "0",
                "nyeri kepala" => "6",
                "TS" => "195",
                "TD" => "100",
                "suhu" => "37.5",
                "nafas" => "26",
                "denyut nadi" => "89",
                "tgl diagnosis" => "13/05/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" =>
                    "G1, G3, G4, G7, G10, G14, G16, G27, G31, G35, G36, G38, G42, G43",
                "Faktor Risiko" => "FR2, FR3, FR8, FR9",
                "Tingkat Keyakinan(%)" => "95",
            ],
            [
                "Kasus" => "K00101",
                "Nama" => "Dedi P",
                "usia" => "47",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "0",
                "nyeri kepala" => "4",
                "TS" => "180",
                "TD" => "90",
                "suhu" => "36",
                "nafas" => "24",
                "denyut nadi" => "89",
                "tgl diagnosis" => "23/06/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" =>
                    "G1, G4, G7, G8, G12, G13, G20, G28, G35, G37, G39, G40, G42",
                "Faktor Risiko" => "FR2, FR5, FR8, FR11",
                "Tingkat Keyakinan(%)" => "92",
            ],
            [
                "Kasus" => "K00044",
                "Nama" => "Yusuf",
                "usia" => "56",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "0",
                "nyeri kepala" => "5",
                "TS" => "160",
                "TD" => "90",
                "suhu" => "36.5",
                "nafas" => "20",
                "denyut nadi" => "82",
                "tgl diagnosis" => "11/06/2016 00:00:00",
                "Diagnosis" => "Thrombosis Stroke",
                "Gejala" =>
                    "G3, G4, G5, G7, G9, G10, G13, G15, G16, G23, G25, G27, G28",
                "Faktor Risiko" => "FR2, FR8, FR11",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00035",
                "Nama" => "Santosa",
                "usia" => "85",
                "jenis kelamin" => "1",
                "kondisi" => "2",
                "kesadaran" => "2",
                "nyeri kepala" => "6",
                "TS" => "160",
                "TD" => "100",
                "suhu" => "37.8",
                "nafas" => "23",
                "denyut nadi" => "89",
                "tgl diagnosis" => "18/04/2016 00:00:00",
                "Diagnosis" => "Intracerebral hemorrhage Stroke",
                "Gejala" =>
                    "G1, G2, G3, G6, G14, G15, G16, G21, G22, G23, G24, G25, G25, G30, G31, G35, G36, G38, G42, G43",
                "Faktor Risiko" => "FR2, FR8",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00036",
                "Nama" => "Billy",
                "usia" => "85",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "7",
                "TS" => "160",
                "TD" => "100",
                "suhu" => "37",
                "nafas" => "20",
                "denyut nadi" => "84",
                "tgl diagnosis" => "06/07/2016 00:00:00",
                "Diagnosis" => "Intracerebral hemorrhage Stroke",
                "Gejala" =>
                    "G1, G2, G3, G4, G7, G8, G9, G11, G15, G16, G22, G23, G25, G26, G27, G28, G32, G34, G35, G38, G42",
                "Faktor Risiko" => "FR1, FR2, FR8",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00120",
                "Nama" => "Jenny",
                "Alamat" => "Banten",
                "usia" => "56",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "0",
                "TS" => "120",
                "TD" => "80",
                "suhu" => "37",
                "nafas" => "24",
                "denyut nadi" => "84",
                "tgl diagnosis" => "15/05/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" =>
                    "G1, G4, G7, G8, G10, G11, G16, G27, G28, G33, G35, G38, G39, G40",
                "Faktor Risiko" => "FR2, FR8",
                "Tingkat Keyakinan(%)" => "92",
            ],
            [
                "Kasus" => "K00121",
                "Nama" => "Yosua",
                "Alamat" => "Banten",
                "usia" => "61",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "0",
                "TS" => "140",
                "TD" => "80",
                "suhu" => "37",
                "nafas" => "24",
                "denyut nadi" => "82",
                "tgl diagnosis" => "15/05/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" => "G4, G8, G15, G17, G18, G20, G27, G28, G29, G35, G39, G40",
                "Faktor Risiko" => "FR3",
                "Tingkat Keyakinan(%)" => "85",
            ],
            [
                "Kasus" => "K00122",
                "Nama" => "Danang",
                "Alamat" => "Banten",
                "usia" => "69",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "0",
                "nyeri kepala" => "3",
                "TS" => "180",
                "TD" => "100",
                "suhu" => "37",
                "nafas" => "24",
                "denyut nadi" => "84",
                "tgl diagnosis" => "16/03/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" =>
                    "G1, G3, G4, G7, G8, G9, G23, G26, G27, G28, G29, G30, G35, G40, G41",
                "Faktor Risiko" => "FR2, FR7, FR8",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00123",
                "Nama" => "Darwis",
                "Alamat" => "Trikora",
                "usia" => "56",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "0",
                "nyeri kepala" => "0",
                "TS" => "180",
                "TD" => "95",
                "suhu" => "36",
                "nafas" => "24",
                "denyut nadi" => "86",
                "tgl diagnosis" => "17/06/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" =>
                    "G2, G3, G7, G8, G9, G10, G11, G14, G15, G20, G27, G35, G41",
                "Faktor Risiko" => "FR3, FR5, FR11",
                "Tingkat Keyakinan(%)" => "95",
            ],
            [
                "Kasus" => "K00124",
                "Nama" => "Desi",
                "Alamat" => "Banten",
                "usia" => "62",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "2",
                "TS" => "170",
                "TD" => "90",
                "suhu" => "37",
                "nafas" => "24",
                "denyut nadi" => "88",
                "tgl diagnosis" => "25/06/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" => "G1, G5, G10, G11, G12, G15, G20, G27, G28, G29, G35, G40",
                "Faktor Risiko" => "FR6, FR8, FR10",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00125",
                "Nama" => "Sadu",
                "Alamat" => "Banten",
                "usia" => "52",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "0",
                "nyeri kepala" => "2",
                "TS" => "160",
                "TD" => "90",
                "suhu" => "36.5",
                "nafas" => "24",
                "denyut nadi" => "88",
                "tgl diagnosis" => "12/03/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" =>
                    "G1, G7, G10, G12, G15, G20, G27, G28, G29, G31, G37, G38, G40, G41, G42",
                "Faktor Risiko" => "FR3, FR11",
                "Tingkat Keyakinan(%)" => "95",
            ],
            [
                "Kasus" => "K00126",
                "Nama" => "Karuna",
                "Alamat" => "Banten",
                "usia" => "54",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "3",
                "TS" => "180",
                "TD" => "90",
                "suhu" => "37",
                "nafas" => "28",
                "denyut nadi" => "90",
                "tgl diagnosis" => "12/04/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" =>
                    "G1, G2, G4, G7, G8, G10, G12, G15, G27, G28, G31, G33, G35, G38, G39, G40, G41",
                "Faktor Risiko" => "FR5, FR7, FR8",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00127",
                "Nama" => "Dika",
                "Alamat" => "Trikora",
                "usia" => "83",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "5",
                "TS" => "130",
                "TD" => "70",
                "suhu" => "37",
                "nafas" => "22",
                "denyut nadi" => "88",
                "tgl diagnosis" => "21/04/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" =>
                    "G1, G2, G8, G11, G12, G15, G17, G18, G20, G21, G23, G25, G31, G34, G35, G37, G38, G40",
                "Faktor Risiko" => "FR6, FR7, FR8, FR10, FR11",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00128",
                "Nama" => "Reina",
                "Alamat" => "Banten",
                "usia" => "79",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "5",
                "TS" => "140",
                "TD" => "90",
                "suhu" => "36",
                "nafas" => "24",
                "denyut nadi" => "82",
                "tgl diagnosis" => "24/05/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" =>
                    "G1, G2, G7, G8, G11, G12, G15, G17, G18, G20, G31, G34, G35, G38, G40",
                "Faktor Risiko" => "FR2, FR7, FR8, FR10",
                "Tingkat Keyakinan(%)" => "85",
            ],
            [
                "Kasus" => "K00129",
                "Nama" => "Erina",
                "Alamat" => "Banten",
                "usia" => "57",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "2",
                "TS" => "180",
                "TD" => "90",
                "suhu" => "36.5",
                "nafas" => "20",
                "denyut nadi" => "90",
                "tgl diagnosis" => "06/04/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" =>
                    "G2, G5, G6, G7, G15, G20, G23, G25, G26, G27, G32, G35, G37, G40",
                "Faktor Risiko" => "FR2, FR5, FR8",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00130",
                "Nama" => "Ade",
                "Alamat" => "Banten",
                "usia" => "66",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "0",
                "nyeri kepala" => "2",
                "TS" => "150",
                "TD" => "90",
                "suhu" => "36",
                "nafas" => "22",
                "denyut nadi" => "88",
                "tgl diagnosis" => "15/05/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" =>
                    "G1, G3, G4, G7, G8, G10, G11, G12, G15, G16, G20, G25, G27, G28, G29, G34, G35, G38, G40",
                "Faktor Risiko" => "FR2, FR5",
                "Tingkat Keyakinan(%)" => "80",
            ],
            [
                "Kasus" => "K00131",
                "Nama" => "Reza",
                "Alamat" => "Trikora",
                "usia" => "69",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "3",
                "TS" => "100",
                "TD" => "70",
                "suhu" => "37",
                "nafas" => "22",
                "denyut nadi" => "90",
                "tgl diagnosis" => "06/05/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" =>
                    "G4, G7, G8, G10, G12, G13, G15, G20, G27, G28, G37, G38, G39, G40",
                "Faktor Risiko" => "FR7, FR8",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00143",
                "Nama" => "Jufri",
                "Alamat" => "Banten",
                "usia" => "46",
                "jenis kelamin" => "1",
                "kondisi" => "2",
                "kesadaran" => "2",
                "nyeri kepala" => "6",
                "TS" => "160",
                "TD" => "100",
                "suhu" => "38.5",
                "nafas" => "24",
                "denyut nadi" => "90",
                "tgl diagnosis" => "21/04/2016 00:00:00",
                "Diagnosis" => "Subarachnoid hemorrhage Stroke",
                "Gejala" => "G4, G6, G7, G13, G14, G15, G16, G35, G36, G38, G42, G43",
                "Faktor Risiko" => "FR2, FR7, FR8",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00144",
                "Nama" => "Gloria",
                "Alamat" => "Banten",
                "usia" => "61",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "8",
                "TS" => "180",
                "TD" => "100",
                "suhu" => "38",
                "nafas" => "26",
                "denyut nadi" => "88",
                "tgl diagnosis" => "21/02/2016 00:00:00",
                "Diagnosis" => "Subarachnoid hemorrhage Stroke",
                "Gejala" =>
                    "G1, G4, G5, G6, G13, G14, G15, G16, G27, G37, G41, G42, G43",
                "Faktor Risiko" => "FR2, FR8",
                "Tingkat Keyakinan(%)" => "92",
            ],
            [
                "Kasus" => "K00145",
                "Nama" => "Hartono",
                "Alamat" => "Banten",
                "usia" => "56",
                "jenis kelamin" => "1",
                "kondisi" => "2",
                "kesadaran" => "1",
                "nyeri kepala" => "8",
                "TS" => "150",
                "TD" => "100",
                "suhu" => "38",
                "nafas" => "22",
                "denyut nadi" => "90",
                "tgl diagnosis" => "29/05/2016 00:00:00",
                "Diagnosis" => "Subarachnoid hemorrhage Stroke",
                "Gejala" =>
                    "G5, G6, G8, G13, G14, G20, G27, G35, G36, G37, G38, G41, G42, G43",
                "Faktor Risiko" => "FR2, FR8",
                "Tingkat Keyakinan(%)" => "95",
            ],
            [
                "Kasus" => "K00146",
                "Nama" => "Endang",
                "Alamat" => "Banten",
                "usia" => "59",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "6",
                "TS" => "190",
                "TD" => "100",
                "suhu" => "37",
                "nafas" => "26",
                "denyut nadi" => "92",
                "tgl diagnosis" => "11/04/2016 00:00:00",
                "Diagnosis" => "Subarachnoid hemorrhage Stroke",
                "Gejala" => "G4, G5, G6, G8, G9, G13, G14, G16, G36, G37, G38, G42",
                "Faktor Risiko" => "FR2, FR7, FR8",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00147",
                "Nama" => "Usmi",
                "Alamat" => "Banten",
                "usia" => "61",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "6",
                "TS" => "180",
                "TD" => "100",
                "suhu" => "38",
                "nafas" => "24",
                "denyut nadi" => "90",
                "tgl diagnosis" => "23/04/2016 00:00:00",
                "Diagnosis" => "Subarachnoid hemorrhage Stroke",
                "Gejala" =>
                    "G2, G3, G4, G5, G7, G14, G15, G16, G19, G21, G22, G23, G24, G25, G26, G27, G28, G31, G35, G38, G41, G42, G43",
                "Faktor Risiko" => "FR2, FR8",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00148",
                "Nama" => "Maria",
                "Alamat" => "Trikora",
                "usia" => "75",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "7",
                "TS" => "140",
                "TD" => "110",
                "suhu" => "38",
                "nafas" => "24",
                "denyut nadi" => "90",
                "tgl diagnosis" => "19/03/2016 00:00:00",
                "Diagnosis" => "Subarachnoid hemorrhage Stroke",
                "Gejala" => "G5, G6, G14, G15, G16, G35, G36, G38, G42, G43",
                "Faktor Risiko" => "FR2, FR6, FR10",
                "Tingkat Keyakinan(%)" => "92",
            ],
            [
                "Kasus" => "K00007",
                "Nama" => "Sutoyo",
                "usia" => "60",
                "jenis kelamin" => "1",
                "kondisi" => "0",
                "kesadaran" => "0",
                "nyeri kepala" => "0",
                "TS" => "150",
                "TD" => "100",
                "suhu" => "36.5",
                "nafas" => "20",
                "denyut nadi" => "88",
                "tgl diagnosis" => "05/04/2016 00:00:00",
                "Diagnosis" => "Embolism Stroke",
                "Gejala" => "G7, G8, G10, G15, G25, G35, G38",
                "Faktor Risiko" => "FR2, FR11",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00150",
                "Nama" => "Utomo",
                "Alamat" => "Banten",
                "usia" => "48",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "2",
                "nyeri kepala" => "8",
                "TS" => "180",
                "TD" => "90",
                "suhu" => "37.5",
                "nafas" => "26",
                "denyut nadi" => "90",
                "tgl diagnosis" => "03/03/2017 00:00:00",
                "Diagnosis" => "Subarachnoid hemorrhage Stroke",
                "Gejala" =>
                    "G4, G5, G6, G7, G8, G14, G16, G27, G35, G36, G38, G41, G42",
                "Faktor Risiko" => "FR2, FR6",
                "Tingkat Keyakinan(%)" => "85",
            ],
            [
                "Kasus" => "K00133",
                "Nama" => "Anna",
                "Alamat" => "Banten",
                "usia" => "66",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "8",
                "TS" => "140",
                "TD" => "100",
                "suhu" => "37.5",
                "nafas" => "22",
                "denyut nadi" => "94",
                "tgl diagnosis" => "11/05/2016 00:00:00",
                "Diagnosis" => "Intracerebral hemorrhage Stroke",
                "Gejala" =>
                    "G4, G5, G6, G7, G14, G15, G16, G23, G27, G29, G32, G34, G37, G38, G42, G43",
                "Faktor Risiko" => "FR2, FR6, FR8",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00134",
                "Nama" => "Sugianto",
                "Alamat" => "Banten",
                "usia" => "64",
                "jenis kelamin" => "1",
                "kondisi" => "2",
                "kesadaran" => "2",
                "nyeri kepala" => "6",
                "TS" => "170",
                "TD" => "100",
                "suhu" => "37",
                "nafas" => "20",
                "denyut nadi" => "86",
                "tgl diagnosis" => "27/02/2016 00:00:00",
                "Diagnosis" => "Intracerebral hemorrhage Stroke",
                "Gejala" =>
                    "G5, G6, G7, G14, G15, G16, G27, G28, G29, G30, G34, G36, G41, G42",
                "Faktor Risiko" => "FR2, FR8, FR11",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00135",
                "Nama" => "Robert",
                "Alamat" => "Trikora",
                "usia" => "65",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "8",
                "TS" => "190",
                "TD" => "100",
                "suhu" => "37",
                "nafas" => "24",
                "denyut nadi" => "88",
                "tgl diagnosis" => "09/02/2016 00:00:00",
                "Diagnosis" => "Intracerebral hemorrhage Stroke",
                "Gejala" =>
                    "G5, G6, G7, G8, G14, G15, G16, G27, G29, G32, G35, G37, G41",
                "Faktor Risiko" => "FR2, FR6, FR10",
                "Tingkat Keyakinan(%)" => "92",
            ],
            [
                "Kasus" => "K00136",
                "Nama" => "Rani",
                "Alamat" => "Banten",
                "usia" => "74",
                "jenis kelamin" => "0",
                "kondisi" => "2",
                "kesadaran" => "1",
                "nyeri kepala" => "8",
                "TS" => "170",
                "TD" => "100",
                "suhu" => "37",
                "nafas" => "24",
                "denyut nadi" => "90",
                "tgl diagnosis" => "11/07/2016 00:00:00",
                "Diagnosis" => "Intracerebral hemorrhage Stroke",
                "Gejala" =>
                    "G5, G6, G7, G8, G14, G15, G16, G27, G28, G30, G32, G33, G34, G35, G36, G38",
                "Faktor Risiko" => "FR2, FR7, FR8",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00137",
                "Nama" => "Trian",
                "Alamat" => "Banten",
                "usia" => "63",
                "jenis kelamin" => "1",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "6",
                "TS" => "140",
                "TD" => "95",
                "suhu" => "37.5",
                "nafas" => "24",
                "denyut nadi" => "90",
                "tgl diagnosis" => "25/04/2016 00:00:00",
                "Diagnosis" => "Intracerebral hemorrhage Stroke",
                "Gejala" =>
                    "G3, G6, G8, G14, G15, G16, G27, G28, G29, G31, G32, G33, G34, G35, G36, G38",
                "Faktor Risiko" => "FR2, FR8",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00138",
                "Nama" => "Bayu",
                "Alamat" => "Banten",
                "usia" => "63",
                "jenis kelamin" => "0",
                "kondisi" => "2",
                "kesadaran" => "1",
                "nyeri kepala" => "7",
                "TS" => "150",
                "TD" => "110",
                "suhu" => "38",
                "nafas" => "22",
                "denyut nadi" => "92",
                "tgl diagnosis" => "05/02/2016 00:00:00",
                "Diagnosis" => "Intracerebral hemorrhage Stroke",
                "Gejala" =>
                    "G6, G7, G8, G14, G15, G16, G27, G29, G32, G35, G36, G42, G43",
                "Faktor Risiko" => "FR2, FR6, FR8, FR10",
                "Tingkat Keyakinan(%)" => "95",
            ],
            [
                "Kasus" => "K00139",
                "Nama" => "Clara",
                "Alamat" => "Banten",
                "usia" => "58",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "8",
                "TS" => "190",
                "TD" => "100",
                "suhu" => "37",
                "nafas" => "22",
                "denyut nadi" => "88",
                "tgl diagnosis" => "21/05/2016 00:00:00",
                "Diagnosis" => "Intracerebral hemorrhage Stroke",
                "Gejala" =>
                    "G1, G6, G7, G8, G12, G14, G15, G16, G27, G29, G32, G34, G35, G36, G38",
                "Faktor Risiko" => "FR2, FR8",
                "Tingkat Keyakinan(%)" => "98",
            ],
            [
                "Kasus" => "K00140",
                "Nama" => "Hartini",
                "Alamat" => "Banten",
                "usia" => "56",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "9",
                "TS" => "170",
                "TD" => "110",
                "suhu" => "36",
                "nafas" => "24",
                "denyut nadi" => "86",
                "tgl diagnosis" => "18/04/2016 00:00:00",
                "Diagnosis" => "Intracerebral hemorrhage Stroke",
                "Gejala" => "G4, G6, G7, G13, G14, G30, G35, G36, G38, G42",
                "Faktor Risiko" => "FR2, FR8",
                "Tingkat Keyakinan(%)" => "85",
            ],
            [
                "Kasus" => "K00180",
                "Nama" => "Yuni",
                "Alamat" => "Banten",
                "usia" => "54",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "0",
                "TS" => "180",
                "TD" => "90",
                "suhu" => "37",
                "nafas" => "24",
                "denyut nadi" => "89",
                "tgl diagnosis" => "15/04/2016 00:00:00",
                "Diagnosis" => "Jantung Koroner",
                "Gejala" => "G5, G7, G28, G30, G37, G38, G39, G40, G42",
                "Faktor Risiko" => "FR2, FR3, FR4",
                "Tingkat Keyakinan(%)" => "85",
            ],
            [
                "Kasus" => "K00178",
                "Nama" => "Deasi",
                "Alamat" => "Banten",
                "usia" => "40",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "0",
                "TS" => "190",
                "TD" => "100",
                "suhu" => "38",
                "nafas" => "25",
                "denyut nadi" => "87",
                "tgl diagnosis" => "04/06/2016 00:00:00",
                "Diagnosis" => "Gagal Jantung Kronik",
                "Gejala" => "G3, G4, G5, G6, G7, G13, G33, G37, G40, G42, G43",
                "Faktor Risiko" => "FR1, FR2, FR3",
                "Tingkat Keyakinan(%)" => "85",
            ],
            [
                "Kasus" => "K00175",
                "Nama" => "Esti",
                "Alamat" => "Trikora",
                "usia" => "66",
                "jenis kelamin" => "0",
                "kondisi" => "1",
                "kesadaran" => "1",
                "nyeri kepala" => "4",
                "TS" => "160",
                "TD" => "90",
                "suhu" => "36",
                "nafas" => "26",
                "denyut nadi" => "88",
                "tgl diagnosis" => "13/06/2016 00:00:00",
                "Diagnosis" => "Jantung Hipertensi",
                "Gejala" => "G3, G4, G5, G6, G7, G13, G38, G39, G40",
                "Faktor Risiko" => "FR1, FR2, FR5",
                "Tingkat Keyakinan(%)" => "90",
            ],
            [
                "Kasus" => "K00169",
                "Nama" => "Ray",
                "Alamat" => "Banten",
                "usia" => "59",
                "jenis kelamin" => "1",
                "kondisi" => "0",
                "kesadaran" => "0",
                "nyeri kepala" => "0",
                "TS" => "140",
                "TD" => "80",
                "suhu" => "37",
                "nafas" => "22",
                "denyut nadi" => "88",
                "tgl diagnosis" => "11/05/2016 00:00:00",
                "Diagnosis" => "Jantung Katup",
                "Gejala" => "G4, G7, G13, G39, G43",
                "Faktor Risiko" => "FR1, FR4, FR11",
                "Tingkat Keyakinan(%)" => "85",
            ],
        ];
        
        
        $data['kasus'] = $tmp2;
        $data['ujikasus'] = $arrUji2;
        
    	return view('generaterule')->with($data);
    }
}
